namespaces:
  core:
    version: 2.7.0-alpha
    data_types:
      Subject:
        species: nwb_subject_termset.yaml
      NWBFile:
        experimenter: experimenter_termset.yaml
        electrodes: TBD
      ElectrodeGroup:
        location: location_termset.yaml
