namespaces:
  core:
    version: 2.7.0
    data_types:
      Subject:
        species:
          termset: nwb_subject_termset.yaml
      NWBFile:
        experimenter:
          termset: experimenter_termset.yaml
