# pinned dependencies to reproduce an entire development environment to use PyNWB with ROS3 support
name: ros3
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.14
  - h5py==3.15.1
  - hdmf==5.1.0
  - matplotlib==3.10.8
  - numpy==2.4.2
  - pandas==2.3.3
  - python-dateutil==2.9.0
  - setuptools
  - pytest==9.0.2
  - fsspec==2026.1.0
  - requests==2.32.5
  - aiohttp==3.13.3
  - pip
  - pip:
    - remfile==0.1.13
    - dandi==0.74.3  # NOTE: dandi is not available on conda for osx-arm64
