# pinned dependencies to reproduce an entire development environment to use PyNWB with ROS3 support
name: ros3
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.14
  - h5py==3.16.0
  - hdmf==6.2.0
  - matplotlib==3.11.0
  - numpy==2.4.3
  - pandas==2.3.3
  - python-dateutil==2.9.0.post0
  - setuptools
  - pytest==9.0.3
  - fsspec==2026.6.0
  - requests==2.34.2
  - aiohttp==3.14.1
  - pip
  - pip:
    - remfile==0.1.13
    - dandi==0.76.5  # NOTE: dandi is not available on conda for osx-arm64
