name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        # Thanks for taking the time to fill out this bug report!
        ### The following information will help us resolve your issue.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Please copy and paste the code you were trying to run that caused the error.

        Feel free to include as little or as much as you think is relevant. This section will be automatically formatted into code, so no need for backticks.
      render: python
    validations:
      required: true
  - type: textarea
    id: traceback
    attributes:
      label: Traceback
      description: |
        Please copy and paste the traceback produced by the error.

        This section will be automatically formatted into code, so no need for backticks.
      render: python
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  - type: dropdown
    id: executable
    attributes:
      label: Python Executable
      options:
        - Conda
        - Python
    validations:
      required: true
  - type: dropdown
    id: python_version
    attributes:
      label: Python Version
      options:
        - "lower version (unsupported)"
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
    validations:
      required: true
  - type: textarea
    id: package_versions
    attributes:
      label: Package Versions
      description: |
        Please share your currently installed Python package versions by calling `pip freeze > environment_for_issue.txt` and uploading the text file along with this issue.

        This helps us determine if there are any secondary or tertiary issues caused by other dependencies.

        You can attach images or log files by clicking this area to highlight it and then dragging files in.
        If GitHub upload is not working, you can also copy and paste the output into this section.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
          required: true
        - label: Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
          required: true
        - label: Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?
          required: true
