name: Generate test files
on:
  workflow_dispatch:
  # pull_request:

permissions:
  contents: read

jobs:
  gen-test-files:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.name }}
      cancel-in-progress: true
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: pynwb-1.5.1, pynwb-version: "1.5.1", python-version: "3.8"}
          - { name: pynwb-2.1.0, pynwb-version: "2.1.0", python-version: "3.9"}
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
          submodules: 'recursive'
          fetch-depth: 0  # tags are required for versioneer to determine the version

      - name: Set up Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          python -m pip install "pynwb==${{ matrix.pynwb-version }}"
          python -m pip list

      - name: Generate test files
        run: |
          python src/pynwb/testing/make_test_files.py

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: test-files-${{ matrix.name }}
          path: |
            src/pynwb/testing/*.nwb
