name: Ruff
on: pull_request

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
      - name: Run ruff
        uses: astral-sh/ruff-action@v4.1.0
