name: Run DANDI read tests
on:
  schedule:
    - cron: '0 6 * * *'  # once per day at 1am ET
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}  # necessary for conda
    steps:
      - name: Cancel non-latest runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0  # tags are required for versioneer to determine the version

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: ros3
          environment-file: environment-ros3.yml
          python-version: "3.11"
          channels: conda-forge
          auto-activate-base: false

      - name: Install run dependencies
        run: |
          python -m pip install dandi pytest
          python -m pip uninstall -y pynwb  # uninstall pynwb
          python -m pip install -e .
          python -m pip list

      - name: Conda reporting
        run: |
          conda info
          conda config --show-sources
          conda list --show-channel-urls

      - name: Run DANDI read tests
        run: |
          pytest -rP tests/read_dandi/
