name: Run DANDI read tests
on:
  pull_request:  # TODO remove me
  schedule:
    - cron: '0 5 * * *'  # once per day at midnight ET
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel non-latest runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0  # tags are required for versioneer to determine the version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install DANDI and install dev branch of PyNWB
        run: |
          python -m pip list
          python -m pip install dandi pytest
          python -m pip uninstall -y pynwb  # uninstall pynwb
          python -m pip install .  # reinstall current branch of pynwb
          python -m pip list

      - name: Run DANDI read tests
        run: |
          pytest tests/read_dandi/
