name: Run DANDI read tests
on:
  # NOTE this is disabled until we can run this systematically instead of randomly
  # so we don't get constant error notifications and waste compute cycles
  # See https://github.com/NeurodataWithoutBorders/pynwb/issues/1804
  # schedule:
  #   - cron: '0 6 * * *'  # once per day at 1am ET
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel non-latest runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0  # tags are required for versioneer to determine the version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install run dependencies
        run: |
          python -m pip install dandi fsspec requests aiohttp pytest
          python -m pip uninstall -y pynwb  # uninstall pynwb
          python -m pip install .
          python -m pip list

      - name: Conda reporting
        run: |
          conda info
          conda config --show-sources
          conda list --show-channel-urls

      - name: Run DANDI read tests
        run: |
          python tests/read_dandi/read_dandi.py
