name: Run style check
on: pull_request

jobs:
  run-flake8:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel any previous incomplete runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        all_but_latest: true
        access_token: ${{ github.token }}

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        python -m pip list

    - name: Run flake8
      run: flake8
